### ISSUE TITLE
support resolving SNS and AD domains

### ISSUE THREAD

**Issue by metasal1** [sendaifun/solana-agent-kit#15]
### Domain Resolution

Agent can resolve domains public key

i.e. agent.resolveAllDomains(domain)

### Lookup Owner

Agent can get all domains owned

i.e. agent.getOwnedAllDomains(owner)

### Get Domains on TLD

Agent can get all domains for a specific TLD

i.e. agent.getOwnedDomainsForTLD(owner, tld)

### Get All Active TLDs

Agent can fetch all the current active TLDs

i.e. agent.getAllDomainsTLDs()

### Get All Registered All Domains

Return all the domains for all the TLDs

i.e. agent.getAllRegisteredAllDomans()

### Get User Main Domain

Get the user’s favourite / main domain
i.e. agent.getMainAllDomainsDomain(owner)

**Comment by thearyanag** [comment]
#29
