### ISSUE TITLE
support Tensor API & SDK

### ISSUE THREAD

**Issue by metasal1** [sendaifun/solana-agent-kit#20]
https://docs.tensor.trade/trade/api-and-sdk

**Comment by dbvora03** [comment]
gm, new docs can be found here: https://dev.tensor.trade/
can pick this up in the coming weeks if still open :)

**Comment by AIFlowML** [comment]
Thinking on try add this.

**Comment by AIFlowML** [comment]
Working on the SDK integration because we did not got the API key we requested yet. 
Since i saw that there is the need to add Actions in the Agent kit i wil treat each tool as an "actions" in a sub folder in tools.

**Comment by AIFlowML** [comment]
> gm, new docs can be found here: https://dev.tensor.trade/ can pick this up in the coming weeks if still open :)

I sent the form and tx any way we can get the api to aslo test that ? :)

**Comment by AIFlowML** [comment]
Impossible to add the SDK from the repo the Solana library conflict i try do API.

**Comment by ubadineke** [comment]
@thearyanag What features are we to implement in particular from Tensor?
