### ISSUE TITLE
Support Gibwork Create Task

### ISSUE THREAD

**Issue by gib-work** [sendaifun/solana-agent-kit#48]
**Is your feature request related to a problem? Please describe.**
Enable AI agents to seamlessly create and manage tasks on the Gibwork

**Describe the solution you'd like**
Agents should have the capability to:
1. Create tasks on Gibwork directly through the toolkit.

**Additional context**
Use Gibwork API `/tasks/public/transaction` documented at https://gibwork.readme.io/reference/taskscontrollercreatepublictransactiontask-1 

For questions or discussions share them on #dev-chat channel on https://discord.gg/TNXJjpRvqN

400 USDC Bounty - https://app.gib.work/bounties/6963c538-dc0b-4a3c-9cd5-0a18c0b20d9e

**Comment by thearyanag** [comment]
#56
