### ISSUE TITLE
NextJS Starter Repo

### ISSUE THREAD

**Issue by thearyanag** [sendaifun/solana-agent-kit#58]
**Is your feature request related to a problem? Please describe.** Feature 
No example repo currently to show how to use in frontend applications 

**Describe the solution you'd like**
Make a repo similar to https://github.com/langchain-ai/langchain-nextjs-template/ which integrates the solana agent kit and people are able to interact directly on a UI

This should go under examples/nextjs-starter-repo

**Comment by yash431garg** [comment]
@thearyanag can we submit one more example repo as there is already few submissions.
