### ISSUE TITLE
Bug with token decimal handling for Trade

### ISSUE THREAD

**Issue by impozzible** [sendaifun/solana-agent-kit#92]
**Describe the bug**
`
const quoteResponse = await (
      await fetch(
        `${JUP_API}/quote?` +
          `inputMint=${inputMint.toString()}` +
          `&outputMint=${outputMint.toString()}` +
          `&amount=${inputAmount * LAMPORTS_PER_SOL}` +
          `&slippageBps=${slippageBps}` +
          `&onlyDirectRoutes=true` +
          `&maxAccounts=20`,
      )
    ).json();
`

This is assuming all input tokes are 9decimals, which is going to cause issues, when trying to swap tokens with decimals other than 9

**Expected behavior**
The function is supposed to detect, the decimals of the input Token and then multiply that with the inputAmount

**Comment by Jason-Tariq** [comment]
Hello @impozzible  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)
